### ISSUE TITLE
Tmall数据集及处理

### ISSUE THREAD

**Issue by znlinux** [CCIIPLab/GCE-GNN#12]
从论文中的数据集下载链接得到的数据集与其数据处理的文件对应不一致，请问这个数据集的链接是对的吗，或者说还有别的数据处理？

**Comment by Mikrokosmos1997** [comment]
论文中使用的Tmall数据集和Nowplaying数据集参考的是论文_Evaluation of Session-based Recommendation Algorithms_，在 #3 中有未经处理的数据集的下载地址，我们的预处理文件在代码中已经给出。

**Comment by znlinux** [comment]
好的，非常感谢！！！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月27日(周二) 下午4:32
收件人: ***@***.***&gt;;
抄送: "Zheng ***@***.******@***.***&gt;;
主题: Re: [CCIIPLab/GCE-GNN] Tmall数据集及处理 (#12)




 
论文中使用的Tmall数据集和Nowplaying数据集参考的是论文_Evaluation of Session-based Recommendation Algorithms_，在 #3 中有未经处理的数据集的下载地址，我们的预处理文件在代码中已经给出。
