### ISSUE TITLE
Original csv of Tmall and Nowplaying

### ISSUE THREAD

**Issue by johnny12150** [CCIIPLab/GCE-GNN#13]
Could you release these CSV files or the code that how you generate sessionId?

**Comment by Mikrokosmos1997** [comment]
Thank you for your interest.

The original csv profile of Tmall and Nowplaying please download from the dropbox link in #3. And the process code is in the folder [dataset](https://github.com/CCIIPLab/GCE-GNN/tree/master/datasets).
