### ISSUE TITLE
build_graph时超参数sample_num在另外两个数据集Tmall和Nowplaying的设置值

### ISSUE THREAD

**Issue by MSJeinlong** [CCIIPLab/GCE-GNN#19]
python build_graph.py时，已经知道diginetica的sample_num设置为12。但是，数据集Tmall和Nowplaying的超参数sample_num没有给出。请问作者可以给出sample_num在数据集Tmall和Nowplaying上进行build_graph时的设置值吗？

**Comment by Mikrokosmos1997** [comment]
感谢关注。
在Tmall和Nowplaying数据集中我们采用了同样的参数设置，即sample_num设置为12。

**Comment by MSJeinlong** [comment]
好的，明白。非常感谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CCIIPLab/GCE-GNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CCIIPLab/GCE-GNN] build_graph时超参数sample_num在另外两个数据集Tmall和Nowplaying的设置值 (Issue #19)





 
感谢关注。
 在Tmall和Nowplaying数据集中我们采用了同样的参数设置，即sample_num设置为12。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
