### ISSUE TITLE
论文公式2

### ISSUE THREAD

**Issue by SiriusXT** [CCIIPLab/GCE-GNN#6]
论文公式2
![图片](https://user-images.githubusercontent.com/37627919/104846698-ce496080-5916-11eb-9a7f-c83bf7332e05.png)和代码
alpha = torch.matmul(torch.cat([extra_vector.unsqueeze(2).repeat(1, 1, neighbor_vector.shape[2], 1), 
                                 neighbor_vector, neighbor_weight.unsqueeze(-1)], -1), self.w_1).squeeze(-1) 不一致，感觉论文公式有误？

**Comment by Mikrokosmos1997** [comment]
感谢对我们工作的关注！
我们的疏忽导致出现不一致，我们按照论文中的公式描述重新修改了代码并进行了测试，更新后的代码将在这几天上传。

**Comment by SiriusXT** [comment]
> 
> 
> 感谢对我们工作的关注！
> 我们的疏忽导致出现不一致，我们按照论文中的公式描述重新修改了代码并进行了测试，更新后的代码将在这几天上传。

另外，文中所提及的反向位置嵌入觉得挺有道理，但是代码中似乎并未体现出反向。

**Comment by Mikrokosmos1997** [comment]
在utils.py文件的[handle_data()](https://github.com/CCIIPLab/GCE-GNN/blob/5054b78f00e2cdb143de952e6574285d88ec422e/utils.py#L20)函数中，我们对原序列进行了反转，这样在与位置向量的计算过程中，第一个位置向量对应着最后一个物品，第二个位置向量对应倒数第二个物品......
我们认为反转原序列比反转位置向量更加简单，同时两种方式都能达到反向位置嵌入的目标。

**Comment by SiriusXT** [comment]
还有一个问题：论文公式3对会话的的求和在代码中体现了，但是对会话的求平均却没发现？

**Comment by Mikrokosmos1997** [comment]
感谢指出。在最新的更新中，已经针对这两点进行修改，使得代码和论文中公式一致。
