### ISSUE TITLE
About preprocessing on Nowplaying

### ISSUE THREAD

**Issue by xiaxin1998** [CCIIPLab/GCE-GNN#7]
Hi,
Thanks for your sharing of this paper!
In your paper, I can't find whether you sort the session based on timestamp in Nowplaying datasets. 
The preprocess is unclear.  Would you mind sharing the preprocessed datasets Nowplaying?
Thanks!

Best regards

**Comment by Mikrokosmos1997** [comment]
Thank you for your interest.
We uploaded the preprocessed Nowplaying dataset. And the preprocessed file for Nowplaying dataset will be uploaded later.

**Comment by xiaxin1998** [comment]
Hi, Could you upload the preprocessed file for Nowplaying dataset?

**Comment by Mikrokosmos1997** [comment]
Thank you for your interest.
We uploaded the preprocessed file for Nowplaying dataset.
