### ISSUE TITLE
关于指标

### ISSUE THREAD

**Issue by Aran-Guo** [CCIIPLab/GCE-GNN#8]
我看了图神经网络在会话推荐的一些文章，发现指标很乱，比如本篇论文中的P，有的地方写成了Recall，但是开源的代码是一样的。请问本文计算的P就是开源代码中的计算方式吗？那他为什么会和SR-GNN报道出来的值不一样呢？

**Comment by Mikrokosmos1997** [comment]
感谢关注。
我们计算P@N指标的方式与SR-GNN一致，报道出来的值不一样主要是由于模型的随机性等因素造成的。
